name = "QuantumGraining"
uuid = "77585022-d976-43ff-a138-80a6f5a3bb8b"
authors = ["Leon Bello"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
